//ToDo Later link it with the real Data and edoit the icon or image Value
class InterestCategories {
  InterestCategories._();
  static final List<String> categories = [
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🎳 Bowling',
    '🍽️ Restaurants',
    '🍢 Street Food Spots',
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🍢 Street Food Spots',
    '🎳 Bowling',
    '🍽️ Restaurants',
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🍢 Street Food Spots',
    '🎳 Bowling',
    '🍽️ Restaurants',
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🍢 Street Food Spots',
    '🎳 Bowling',
    '🍽️ Restaurants',
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🍢 Street Food Spots',
    '🎳 Bowling',
    '🍽️ Restaurants',
    '☕ Cafés',
    '🥐 Bakeries',
    '🎵 Music',
    '🍢 Street Food Spots',
    '🎳 Bowling',
    '🍽️ Restaurants',
  ];
}
