// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdSXS8j6SyOA0Fdxoh1QpxMfG4eD_Nh7k',
    appId: '1:441568674116:web:6cfd2b5b76c98208d69711',
    messagingSenderId: '441568674116',
    projectId: 'mind-trip-8abdc',
    authDomain: 'mind-trip-8abdc.firebaseapp.com',
    storageBucket: 'mind-trip-8abdc.firebasestorage.app',
    measurementId: 'G-T5WGSR0N1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6fKue8-UT6fvF8pEh7Ur95CkMY68cPb8',
    appId: '1:441568674116:android:63544829f7ddac02d69711',
    messagingSenderId: '441568674116',
    projectId: 'mind-trip-8abdc',
    storageBucket: 'mind-trip-8abdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSE9zersl4mn1WibD0JfBK2gcBV1JbMJA',
    appId: '1:441568674116:ios:6a230933c5c10285d69711',
    messagingSenderId: '441568674116',
    projectId: 'mind-trip-8abdc',
    storageBucket: 'mind-trip-8abdc.firebasestorage.app',
    iosBundleId: 'com.example.mindtrip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSE9zersl4mn1WibD0JfBK2gcBV1JbMJA',
    appId: '1:441568674116:ios:6a230933c5c10285d69711',
    messagingSenderId: '441568674116',
    projectId: 'mind-trip-8abdc',
    storageBucket: 'mind-trip-8abdc.firebasestorage.app',
    iosBundleId: 'com.example.mindtrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdSXS8j6SyOA0Fdxoh1QpxMfG4eD_Nh7k',
    appId: '1:441568674116:web:8a2e7df664335dcdd69711',
    messagingSenderId: '441568674116',
    projectId: 'mind-trip-8abdc',
    authDomain: 'mind-trip-8abdc.firebaseapp.com',
    storageBucket: 'mind-trip-8abdc.firebasestorage.app',
    measurementId: 'G-3MM2TFE89H',
  );
}
