// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mindtrip/core/enums/place_badge.dart';
import 'package:mindtrip/core/enums/place_category.dart';
import 'package:mindtrip/core/shared/data/models/location_model.dart';
import 'package:mindtrip/core/shared/data/models/place_model.dart';
import 'package:mindtrip/features/ai_planner/data/models/trip_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocationModelAdapter());
    registerAdapter(PlaceBadgeAdapter());
    registerAdapter(PlaceCategoryAdapter());
    registerAdapter(PlaceModelAdapter());
    registerAdapter(TripModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(LocationModelAdapter());
    registerAdapter(PlaceBadgeAdapter());
    registerAdapter(PlaceCategoryAdapter());
    registerAdapter(PlaceModelAdapter());
    registerAdapter(TripModelAdapter());
  }
}
