// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mindtrip/core/enums/place_badge.dart';
import 'package:mindtrip/core/enums/place_category.dart';
import 'package:mindtrip/core/enums/place_city.dart';
import 'package:mindtrip/core/shared/data/models/banner_model.dart';
import 'package:mindtrip/core/shared/data/models/favorite_trip_model.dart';
import 'package:mindtrip/core/shared/data/models/location_model.dart';
import 'package:mindtrip/core/shared/data/models/place_model.dart';
import 'package:mindtrip/core/shared/data/models/planner_preview_model.dart';
import 'package:mindtrip/features/search/data/models/recent_search_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BannerModelAdapter());
    registerAdapter(FavoriteTripModelAdapter());
    registerAdapter(LocationModelAdapter());
    registerAdapter(PlaceBadgeAdapter());
    registerAdapter(PlaceCategoryAdapter());
    registerAdapter(PlaceCityAdapter());
    registerAdapter(PlaceModelAdapter());
    registerAdapter(PlannerPreviewModelAdapter());
    registerAdapter(PlannerStopModelAdapter());
    registerAdapter(RecentSearchModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BannerModelAdapter());
    registerAdapter(FavoriteTripModelAdapter());
    registerAdapter(LocationModelAdapter());
    registerAdapter(PlaceBadgeAdapter());
    registerAdapter(PlaceCategoryAdapter());
    registerAdapter(PlaceCityAdapter());
    registerAdapter(PlaceModelAdapter());
    registerAdapter(PlannerPreviewModelAdapter());
    registerAdapter(PlannerStopModelAdapter());
    registerAdapter(RecentSearchModelAdapter());
  }
}
