import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:mindtrip/core/shared/routes/app_routes.dart';
import 'package:mindtrip/features/ai_planner/presentation/widgets/chat_bot/chat_bot_image.dart';

class AiChatBotButton extends StatelessWidget {
  const AiChatBotButton({super.key, required this.sessionId});

  /// The session ID generated by the parent screen (planner flow).
  /// It is shared with the chat screen so conversation context is continuous.
  final String sessionId;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () {
        context.push(AppRoutes.aiPlannerChat, extra: sessionId);
      },
      child: ChatBotImage(width: 62, height: 62, isButton: true),
    );
  }
}
